version: '3.1'

services:
  postgres:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:
